version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0
  aws-cli: circleci/aws-cli@0.1.9

jobs:
  deploy-to-staging:
    docker:
      - image: circleci/python:3.7
    steps:
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ID_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_REGION
      - run:
          name: Install jq
          command: |
            sudo apt update
            sudo apt install jq
      - run:
          name: Install ecs deploy
          command: |
            curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee /usr/bin/ecs-deploy
            sudo chmod +x /usr/bin/ecs-deploy
      - run:
          name: Premote target image
          command: |
            ecs-deploy --region $AWS_REGION \
            --cluster $CLUSTER_NAME \
            --service-name transactions-api-staging \
            --image "$AWS_ECR_HOST/$AWS_ECR_PATH:$CIRCLE_SHA1"
            --timeout 104400 \
            --use-latest-task-def
          no_output_timeout: 30m

workflows:
  build_and_deploy:
      jobs:
      - aws-ecr/build_and_push_image:
          name: build_and_push_image
          account-url: AWS_ECR_HOST
          repo: $AWS_ECR_PATH
          aws-access-key-id: AWS_ID_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
#          filters:
#            branches:
#              only: master
      - deploy-to-staging:
          requires:
            - build_and_push_image
#      - aws-ecs/deploy-service-update:
#          name: deploy-staging
#          requires:
#            - build_and_push_image
#          aws-access-key-id: $AWS_ID_KEY
#          aws-secret-access-key: $AWS_SECRET_KEY
#          aws-region: $AWS_REGION
#          family: 'transactions-api-staging'
#          cluster-name: $CLUSTER_NAME
#          container-image-name-updates: "container=transactions-api-staging-service,tag=${CIRCLE_SHA1}"
#          verify-revision-is-deployed: true
#      - permit_production_release:
#          type: approval
#          requires:
#            - deploy-staging
#      - aws-ecs/deploy-service-update:
#          name: deploy-production
#          requires:
#            - permit_production_release
#          family: 'transactions-api-production'
#          cluster-name: $CLUSTER_NAME
#          container-image-name-updates: 'container=transactions-api-production-service,tag=${CIRCLE_SHA1}'
#          verify-revision-is-deployed: true
